<?php
declare(strict_types=1);

namespace Nemesis\Documentation;

class SwaggerGenerator {
    protected $info = [];
    protected $paths = [];
    protected $components = [];

    public function __construct($title = 'API Documentation', $version = '1.0.0') {
        $this->info = [
            'title' => $title,
            'version' => $version,
            'description' => 'API documentation generated by Nemesis Framework'
        ];
    }

    public function addPath($path, $method, $config) {
        if (!isset($this->paths[$path])) {
            $this->paths[$path] = [];
        }

        $this->paths[$path][strtolower($method)] = $config;
        return $this;
    }

    public function addSchema($name, $schema) {
        if (!isset($this->components['schemas'])) {
            $this->components['schemas'] = [];
        }

        $this->components['schemas'][$name] = $schema;
        return $this;
    }

    public function generate() {
        return [
            'openapi' => '3.0.0',
            'info' => $this->info,
            'paths' => $this->paths,
            'components' => $this->components
        ];
    }

    public function toJson() {
        return json_encode($this->generate(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    }

    public function toYaml() {
        // Simplified YAML conversion (in production, use a proper YAML library)
        $spec = $this->generate();
        return "# OpenAPI 3.0 Specification\n" . $this->arrayToYaml($spec);
    }

    protected function arrayToYaml($array, $indent = 0) {
        $yaml = '';
        $spaces = str_repeat('  ', $indent);

        foreach ($array as $key => $value) {
            if (is_array($value)) {
                $yaml .= $spaces . $key . ":\n";
                $yaml .= $this->arrayToYaml($value, $indent + 1);
            } else {
                $yaml .= $spaces . $key . ': ' . $value . "\n";
            }
        }

        return $yaml;
    }

    // Annotation-based documentation (simplified)
    public static function fromAnnotations($controllersPath) {
        $swagger = new self();

        // Scan controllers for PHPDoc annotations
        // This is a placeholder - real implementation would parse annotations

        return $swagger;
    }

    public function serve() {
        header('Content-Type: application/json');
        echo $this->toJson();
        exit;
    }
}
